# Generated by Django 4.0.5 on 2022-06-09 23:41

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('postagem', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 23, 41, 29, 939458, tzinfo=utc))),
            ],
        ),
    ]
